version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mi-app-oracle
    container_name: mi-app-container
    environment:
      SPRING_DATASOURCE_USERNAME: Admin
      SPRING_DATASOURCE_PASSWORD: OracleCloud123
    ports:
      - "8080:8080" # Map container port 8080 to host port 8080
    volumes:
      - ./Wallet_NKYTD6DF15M2NHAO:/app/wallet
    restart: unless-stopped
