services:
  api-product-archetype:
    image: matfuentesv/api-product-archetype:1.0.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@FullStackIII_tp?TNS_ADMIN=/miapp/oracle_wallet/
      SPRING_DATASOURCE_USERNAME: Admin
      SPRING_DATASOURCE_PASSWORD: OracleCloud123
    restart: always
